### PR TITLE
Fix BITFIELD command

### LINKED ISSUE #98: Fix BITFIELD command
The current `bitField` implementation has the following problems:
1. it doesn't allow mixed order of different commands like in the example below (order matters).
2. it cannot parse current output because it is an array of integers and if there is overflow failure, it will have NULL multistring output (`$-1`) as an element of an output array.

**Example:**
```
BITFIELD key INCRBY u4 0 1 OVERFLOW FAIL INCRBY u4 0 9223372036854775807 INCRBY u4 0 1 INCRBY u4 0 1
*4
:10
$-1
:11
:12
```

### PR DESCRIPTION
**Pull request by anovakovic01**
This PR fixes #98.

**Summary:**
1. Fixed input and output for `bitField` command.
2. Added tests for the new `ChunkOptionalLongOutput`.
3. Added tests for `bitField` command.

**Note:** It's not possible to call `bitField` with key as the only parameter and get an empty array using current API, but I think that this is not a big issue as it isn't useful use-case.

### CODE REVIEW

File: redis/src/main/scala/zio/redis/Input.scala [hunk 1]
```diff
@@ -31,23 +31,16 @@ object Input {
...
+  case object BitFieldCommandInput extends Input[BitFieldCommand] {
+    def encode(data: BitFieldCommand): Chunk[String] =
+      data match {
+        case BitFieldCommand.BitFieldGet(t, o)     => Chunk(wrap("GET"), wrap(t.stringify), wrap(o.toString))
+        case BitFieldCommand.BitFieldSet(t, o, v)  =>
+          Chunk(wrap("SET"), wrap(t.stringify), wrap(o.toString), wrap(v.toString))
+        case BitFieldCommand.BitFieldIncr(t, o, i) =>
+          Chunk(wrap("INCRBY"), wrap(t.stringify), wrap(o.toString), wrap(i.toString))
+        case bfo: BitFieldCommand.BitFieldOverflow => Chunk(wrap("OVERFLOW"), wrap(bfo.stringify))
+      }
```
Comment (mijicd) [inline redis/src/main/scala/zio/redis/Input.scala:43]: Let's add `import BitFieldCommand._` to this function, it'll make things slightly more readable.
