### PR TITLE
Fix bulkstring decoder when it ends with a '\n' character

### LINKED ISSUE #613: BulkString with newline character at the end causes process to lock
If a bulkString has a '\n' at the end of the actual string data, RespValue Decoder produces a lock in the current RedisExecutor.

One way to reproduce it is using PING command that returns a BulkString if a string argument is provided.
```scala
testM("PING with a string argument will lock executor") {
  ping(Some("Hello with a newline\n")).map(assert(_)(equalTo("Hello with a newline\n")))
}
```
Executing it (bloop test redis-test -- -t "PING with a string argument will lock executor"),
will cause a timeout exception (Timeout of 1 m exceeded.)

I was facing this issue trying to implement #612 (decoding a client info response returned from the server as a bulk string, client info data has a newline char at the end of the record).

I think the problem is located at RespValue Decoder
```scala
Transducer.utf8Decode >>> Transducer.splitLines >>> processLine
```

Transduder.splitLines will produce an empty line after the bulk string data,
causing an incosistent state in the feed method,
when the bulk string data is completed, state becomes 'Done' and then, with the new empty line, it becomes 'Failed'.

A simple solution seems to have a transition from 'Start' to 'Start' when a empty line is feeded.

Could make a PR if it makes sense.

### PR DESCRIPTION
**Pull request by jgoday**
Fixes #613.

As described in #613, If a bulkString has a '\n' at the end of the actual string data, RespValue Decoder produces a lock in the current RedisExecutor.

This simple PR adds a transition from Start to Start, when the line is blank, in RespValue.feed.

### CODE REVIEW

**Comment by jgoday** [comment]
It seems that the error/locking remains when a bulk string has a '\n' character in a position other than the end.
I will try to fixit tomorrow

**Comment by mijicd** [comment]
@jgoday Thank you. I have marked the PR as draft for now.

**Comment by jgoday** [comment]
Updated to replace RespValue.State ExpectingBulkString to CollectingBulkString,
allowing to gather whole bulk string across several lines.

**Comment by mijicd** [comment]
@jgoday Ready for review?

**Comment by jgoday** [comment]
> @jgoday Ready for review? If so, please convert the draft to PR 🥂

Sure, just converted it to PR again.

File: redis/src/main/scala/zio/redis/RespValue.scala [hunk 1]
```diff
@@ -146,16 +150,24 @@ object RespValue {
...
 
-          case ExpectingBulk => Done(bulkString(line))
-          case _             => Failed
+          case CollectingBulkString(rem, vals, index) =>
+            val allLineBytes = Chunk.fromArray(line.getBytes(StandardCharsets.UTF_8))
+            val lineBytes    = if (allLineBytes.length > rem) allLineBytes.slice(0, rem) else allLineBytes
+            val bytesBuilder = if (index > 0) vals ++= (Lf +: lineBytes) else vals ++= lineBytes
+
+            if (rem - lineBytes.length > 0)
+              CollectingBulkString(rem - lineBytes.length - 1, bytesBuilder, index + lineBytes.length)
```
Comment (mijicd) [inline redis/src/main/scala/zio/redis/RespValue.scala:159]: I'd factor out these length calls.

File: redis/src/main/scala/zio/redis/RespValue.scala [hunk 2]
```diff
@@ -146,16 +150,24 @@ object RespValue {
               case state              => CollectingArray(rem, vals, state.feed)
             }
 
-          case ExpectingBulk => Done(bulkString(line))
-          case _             => Failed
+          case CollectingBulkString(rem, vals, index) =>
+            val allLineBytes = Chunk.fromArray(line.getBytes(StandardCharsets.UTF_8))
```
Comment (mijicd) [inline redis/src/main/scala/zio/redis/RespValue.scala:154]: I'm wondering if it's possible to postpone (or limit) the UTF8 encode & decode, as it will be quite expensive. :thinking:

**Review by mijicd — COMMENTED** [review]
I suspect that this issue might be present "universally", not only for bulk strings (i.e. presence of newlines in 'content'). Perhaps we can expand the test suite or discard that option.

File: redis/src/test/scala/zio/redis/ConnectionSpec.scala [hunk 3]
```diff
@@ -159,6 +159,13 @@ trait ConnectionSpec extends BaseSpec {
         },
         testM("PING with input") {
           ping(Some("Hello")).map(assert(_)(equalTo("Hello")))
+        },
+        testM("PING with a string argument will not lock executor") {
+          ping(Some("Hello with a newline\n")).map(assert(_)(equalTo("Hello with a newline\n")))
```
Comment (anatolysergeev) [inline redis/src/test/scala/zio/redis/ConnectionSpec.scala:164]: Is everything going to be ok if in the end would be \r ?

**Comment by jxnu-liguobin** [comment]
> I suspect that this issue might be present "universally", not only for bulk strings (i.e. presence of newlines in 'content'). Perhaps we can expand the test suite or discard that option.

The issue I created earlier may also be because of this?

File: redis/src/main/scala/zio/redis/RespValue.scala (hunk 1 above)
Comment (jgoday) [reply redis/src/main/scala/zio/redis/RespValue.scala]: I have updated it to simplify the CollectinngBulkString logic.
  As stated in redis RESP spec about arrays, I think we can replace Transduce.splitLines for Transduce.splitOn(CrLf),
 so unnecessary complications are avoided when it comes to recomposing the possible value of the bulk string.

File: redis/src/main/scala/zio/redis/RespValue.scala (hunk 2 above)
Comment (jgoday) [reply redis/src/main/scala/zio/redis/RespValue.scala]: We can append bulk string lines using a stringbuilder and then, only at the end encoding as UTF bytes.

File: redis/src/test/scala/zio/redis/ConnectionSpec.scala (hunk 3 above)
Comment (jgoday) [reply redis/src/test/scala/zio/redis/ConnectionSpec.scala:164]: You are right, as mentioned early, if we split only crlf, then we can recompose the exact value of the bulk string, avoiding an ambiguity between Lf and CrLf

**Comment by mijicd** [comment]
@jgoday Please resolve conflicts so that we can proceed with review & (hopefully :) ) merge :pray:

**Comment by jgoday** [comment]
> @jgoday Please resolve conflicts so that we can proceed with review & (hopefully :) ) merge pray

Sorry again for the delay,
I just have merge and squash it.

**Review by mijicd — APPROVED** [review]
